import {
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bot,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsRight,
  Clock,
  Code,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  GitBranch,
  Home,
  Key,
  Layers,
  Layers3,
  LayoutDashboard,
  Lightbulb,
  Loader2,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  Network,
  Phone,
  Plus,
  Scale,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  TrendingUp,
  User,
  Users,
  X,
  Zap,
  Calendar,
} from "lucide-react";

// Icon map
// One place to add, remove, or swap icons across the entire app.
// To change an icon globally — update it here. No component changes needed.

export const iconMap = {
  // navigation
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-right": ChevronsRight,
  "external-link": ExternalLink,
  menu: Menu,
  close: X,
  x: X,

  // actions
  search: Search,
  settings: Settings,
  plus: Plus,
  minus: Minus,
  check: Check,
  "check-circle-2": CheckCircle2,
  download: Download,
  key: Key,
  eye: Eye,
  "eye-off": EyeOff,
  "loader-2": Loader2,

  // communication & contact
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  "message-square": MessageSquare,
  "map-pin": MapPin,
  users: Users,

  // navigation items
  home: Home,
  star: Star,

  // dashboard features & landing items
  dashboard: LayoutDashboard,
  sessions: Clock,
  analytics: Star,
  code: Code,
  "git-branch": GitBranch,
  shield: Shield,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  user: User,
  zap: Zap,
  "trending-up": TrendingUp,
  "layers-3": Layers3,
  layers: Layers,
  "bar-chart-3": BarChart3,
  "book-open": BookOpen,
  bot: Bot,
  cpu: Cpu,
  database: Database,
  network: Network,
  lightbulb: Lightbulb,
  scale: Scale,

  // theme
  sun: Sun,
  moon: Moon,
} as const;

export const lucideIconRegistry = {
  ArrowRight: "arrow-right",
  ArrowUpRight: "arrow-up-right",
  ChevronDown: "chevron-down",
  ChevronLeft: "chevron-left",
  ChevronRight: "chevron-right",
  ChevronUp: "chevron-up",
  ChevronsRight: "chevrons-right",
  Close: "close",
  X: "close",
  Menu: "menu",
  Search: "search",
  Settings: "settings",
  Plus: "plus",
  Minus: "minus",
  Check: "check",
  CheckCircle2: "check-circle-2",
  Download: "download",
  Key: "key",
  Eye: "eye",
  EyeOff: "eye-off",
  Loader2: "loader-2",
  Phone: "phone",
  Home: "home",
  Mail: "mail",
  Calendar: "calendar",
  MapPin: "map-pin",
  Star: "star",
  MessageSquare: "message-square",
  Users: "users",
  Dashboard: "dashboard",
  Sessions: "sessions",
  Analytics: "analytics",
  Code: "code",
  GitBranch: "git-branch",
  Shield: "shield",
  ShieldCheck: "shield-check",
  Sparkles: "sparkles",
  User: "user",
  Zap: "zap",
  TrendingUp: "trending-up",
  Layers3: "layers-3",
  Layers: "layers",
  BarChart3: "bar-chart-3",
  BookOpen: "book-open",
  Bot: "bot",
  Cpu: "cpu",
  Database: "database",
  Network: "network",
  Lightbulb: "lightbulb",
  Scale: "scale",
  Sun: "sun",
  Moon: "moon",
} as const satisfies Record<string, IconName>;

// Types
export type IconName = keyof typeof iconMap;
